apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server-project
  replicas: 1 
  template:
    metadata:
      labels:
        app: server-project
    spec:
      containers:
      - name: server-project
        image: farabashorun/server-project
        ports:
        - containerPort: 8000
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-project
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
