apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server-project
  replicas: 1 
  template:
    metadata:
      labels:
        app: server-project
    spec:
      containers:
      - name: server-project
        image: server-project
        ports:
        - containerPort: 8000
